### ISSUE TITLE
An error occurred when running Python train_valid_reference_main.py

### ISSUE THREAD

**Issue by hjj-lmx** [xuebinqin/DIS#124]
Traceback (most recent call last):
  File "E:\DIS-main\DIS-main\IS-Net\train_valid_inference_main.py", line 731, in <module>
    main(train_datasets,
  File "E:\DIS-main\DIS-main\IS-Net\train_valid_inference_main.py", line 600, in main
    train(net,
  File "E:\DIS-main\DIS-main\IS-Net\train_valid_inference_main.py", line 319, in train
    for i, data in enumerate(gos_dataloader):
  File "E:\DIS-main\DIS-main\venv\lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
  File "E:\DIS-main\DIS-main\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "E:\DIS-main\DIS-main\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1372, in _process_data
    data.reraise()
  File "E:\DIS-main\DIS-main\venv\lib\site-packages\torch\_utils.py", line 705, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "E:\DIS-main\DIS-main\venv\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "E:\DIS-main\DIS-main\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\DIS-main\DIS-main\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\DIS-main\DIS-main\IS-Net\data_loader_cache.py", line 383, in __getitem__
    sample = self.transform(sample)
  File "E:\DIS-main\DIS-main\venv\lib\site-packages\torchvision\transforms\transforms.py", line 95, in __call__
    img = t(img)
  File "E:\DIS-main\DIS-main\IS-Net\data_loader_cache.py", line 192, in __call__
    image = normalize(image,self.mean,self.std)
  File "E:\DIS-main\DIS-main\venv\lib\site-packages\torchvision\transforms\functional.py", line 350, in normalize
    return F_t.normalize(tensor, mean=mean, std=std, inplace=inplace)
  File "E:\DIS-main\DIS-main\venv\lib\site-packages\torchvision\transforms\_functional_tensor.py", line 926, in normalize
    return tensor.sub_(mean).div_(std)
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0

**Comment by Kaustubh-cpu** [comment]
@hjj-lmx  your images contain 4 channel(alpha channel) which is not accepted by the code To resolve this error you need to remove the Alpha channel from your training data

**Comment by hjj-lmx** [comment]
> @hjj-lmx 您的图像包含 4 个通道（Alpha 通道），代码不接受要解决此错误，您需要从训练数据中删除 Alpha 通道
isnet-general-use.pth, How to continue training on this model and implement it
