### ISSUE TITLE
What amount of video memory needed for training? (getting torch.cuda.OutOfMemoryError: CUDA on 16GB card)

### ISSUE THREAD

**Issue by VladMVLX** [xuebinqin/DIS#65]
Hello, 
thank you for amazing work.

Can you please advise what amount of video memory needed for training? 

I am trying to run **train_valid_inference_main.py** following training instructions on test training dataset with 50 images and GTs in it, but training failing with error:

`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 16.00 GiB total capacity; 15.20 GiB already allocated; 0 bytes free; 15.25 GiB reserved in total by PyTorch)`
almost immediately after started.

I am running training code on machine with 64 GB of RAM and RTX 3080TI 16 GB of VRAM.

Can someone advise if I am doing something wrong or needed some more configuration, or just need more fat video card?

**Comment by VladMVLX** [comment]
Trying to switch to CPU device (commented out all cuda checks)
gives such error:
```
C:\Program Files\Python310\lib\site-packages\torch\nn\functional.py:1967: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
Traceback (most recent call last):
  File "I:\Tests\DIS\IS-Net\train_valid_inference_main.py", line 744, in <module>
    main(train_datasets,
  File "I:\Tests\DIS\IS-Net\train_valid_inference_main.py", line 599, in main
    train(net,
  File "I:\Tests\DIS\IS-Net\train_valid_inference_main.py", line 358, in train
    ds,_ = net(inputs_v)
ValueError: too many values to unpack (expected 2)
```

Any advise what it can be?

**Comment by VladMVLX** [comment]
RTX 4090 with 24GB of video RAM seams like working well, closing this issue.
