### ISSUE TITLE
Not able to save image: ValueError: Can't write images with one color channel.

### ISSUE THREAD

**Issue by wern44** [xuebinqin/DIS#87]
Hello,
I hope someone is able to help me here as I am completely stuck.
I get the follwoing error when running the inference:
ValueError: Can't write images with one color channel. -> triggered on line 53 when saving the image.

I already tried different things (cmap="Gray") etc. but nothing worked.

Thank you for any ideas!

Trace:
Traceback (most recent call last):
  File "main\IS-Net\inference.py", line 53, in <module>
    io.imsave(os.path.join(result_path,im_name+".png"),(result*255).permute(1,2,0).cpu().data.numpy().astype(np.uint8))
  File "R:\OneDrive\Kiart\Batch\Python\DIS_AI\DIS-main\venv\lib\site-packages\skimage\io\_io.py", line 143, in imsave
    return call_plugin('imsave', fname, arr, plugin=plugin, **plugin_args)
  File "main\venv\lib\site-packages\skimage\io\manage_plugins.py", line 205, in call_plugin
    return func(*args, **kwargs)
  File "main\venv\lib\site-packages\imageio\v3.py", line 147, in imwrite
    encoded = img_file.write(image, **kwargs)
  File "main\venv\lib\site-packages\imageio\plugins\pillow.py", line 405, in write
    raise ValueError("Can't write images with one color channel.")
ValueError: Can't write images with one color channel.

**Comment by CzakuGim** [comment]
Quick fix:
Use:

```python
import cv2
cv2.imwrite(os.path.join(result_path,im_name+".png"),(result*255).permute(1,2,0).cpu().data.numpy().astype(np.uint8))
```

Instead of:
```python
io.imsave(os.path.join(result_path,im_name+".png"),(result*255).permute(1,2,0).cpu().data.numpy().astype(np.uint8))
```

**Comment by wern44** [comment]
Thank you for your help! It worked perfectly.
